# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-19 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post_blog',
            options={'ordering': ['time']},
        ),
        migrations.AlterField(
            model_name='post_blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Imagies_from_site'),
        ),
    ]
