# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_author_femalemanager_malemanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_blog',
            name='image',
            field=models.ImageField(blank=True, help_text='help text', null=True, upload_to='Imagies_from_site'),
        ),
        migrations.AlterField(
            model_name='post_blog',
            name='title',
            field=models.CharField(help_text='This is the help text', max_length=140),
        ),
    ]
